### ISSUE TITLE
libmdbx submodule doesn't get installed

### ISSUE THREAD

**Issue by seruum** [snej/nimdbx#8]
Using nimble install, it installed cleanly without error.

A program with only an import and an echo will not build.
Looks like the libmdbx files are missing, but I can't find a way to get them added.
..................................................
stack trace: (most recent call last)
/home/jason/.nimble/pkgs/nimterop-0.6.13/nimterop/build/getheader.nim(485, 23)
/home/jason/.nimble/pkgs/nimterop-0.6.13/nimterop/build/getheader.nim(238, 11) buildLibrary
/home/jason/Local_Install/nim-1.4.2/lib/system/assertions.nim(30, 26) failedAssertImpl
/home/jason/Local_Install/nim-1.4.2/lib/system/assertions.nim(23, 11) raiseAssert
/home/jason/Local_Install/nim-1.4.2/lib/system/fatal.nim(49, 5) sysFatal
/home/jason/.nimble/pkgs/nimdbx-0.4.0/nimdbx/private/libmdbx.nim(17, 10) template/generic instantiation of `getHeader` from here
/home/jason/Local_Install/nim-1.4.2/lib/system/fatal.nim(49, 5) Error: unhandled exception: /home/jason/.nimble/pkgs/nimterop-0.6.13/nimterop/build/getheader.nim(238, 12) `buildStatus.built` 
Build configuration failed - No build files found in /home/jason/.nimble/nimdbx/vendor/libmdbx
 [AssertionDefect]
The terminal process "/bin/bash '-c', 'nim c -r -o:dbxnim /home/jason/Files/Projects/Nim/Test/dbxnim.nim'" terminated with exit code: 1.

**Comment by seruum** [comment]
Didn't mention it before, but this was on Linux. ArchLinux to be specific.
I got it to work by cloning libmdbx into /home/jason/.nimble/nimdbx/vendor. Didn't catch that it the directory structure didn't follow the norm for nimble, in that it wasn't in pkgs/nimdbx-x.x.x
Not sure if the package was expected to create that directory or not, or if that was the place it was expected.

**Comment by snej** [comment]
libmdbx is a Git submodule. Does nimble not check out submodules?

**Comment by snej** [comment]
Fixed now. `nimble install` should work.
